Satellite-im/Warp

extensions/warp-fs-ipfs/src/lib.rs
extensions/warp-fs-memory/src/lib.rs
extensions/warp-fs-memory/src/native.rs
extensions/warp-fs-memory/src/wasm.rs
extensions/warp-fs-storj/src/s3.rs
extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-solana/examples/solana-friends.rs
extensions/warp-mp-solana/examples/solana-identity.rs
extensions/warp-mp-solana/src/lib.rs
extensions/warp-pd-flatfile/src/lib.rs
extensions/warp-pd-memory/src/lib.rs
extensions/warp-pd-stretto/src/lib.rs
extensions/warp-rg-ipfs/examples/ipfs_messenger.rs
extensions/warp-rg-ipfs/examples/rg_messenger_persistent.rs
extensions/warp-rg-ipfs/examples/solana_messenger.rs
extensions/warp-rg-ipfs/src/lib.rs
extensions/warp-rg-ipfs/src/store/direct.rs
warp-bin/src/http/rocket/constellation.rs
warp-bin/src/http/rocket/mod.rs
warp-bin/src/main.rs
warp-bin/src/manager.rs
warp-bin/src/terminal/mod.rs
warp-bin/src/terminal/ui.rs
warp/src/constellation/mod.rs
warp/src/multipass/mod.rs
warp/src/pocket_dimension/mod.rs
warp/src/raygun/mod.rs

This should, in theory, improve performance where there can be multiple readers for functions that dont need an exclusive lock but should take note that the writer may be starved on linux (which may impact other linux-based systems like android), though that has yet to be seen under the crate that handles the current sync primitives
Replaces Mutex with RwLock where necessary 
WARP-144

refactor(misc): Use RwLock instead of Mutex

---

extensions/warp-rg-ipfs/examples/ipfs_messenger.rs
extensions/warp-rg-ipfs/examples/messenger.rs
extensions/warp-rg-ipfs/examples/rg_messenger_persistent.rs
extensions/warp-rg-ipfs/examples/solana_messenger.rs
extensions/warp-rg-ipfs/src/lib.rs
extensions/warp-rg-ipfs/src/spam_filter/classifiers/bayes_classifier/mod.rs
extensions/warp-rg-ipfs/src/spam_filter/mod.rs
extensions/warp-rg-ipfs/src/store/direct.rs
extensions/warp-rg-ipfs/src/store/mod.rs
warp/src/raygun/group.rs
warp/src/raygun/mod.rs

This PR removes SenderId and other wrappers that were around `Uid` to use UUID or DID where its needed. This is due to the lack of use case around using a UUID as a sender. 
This PR also change the group structure in preparation of a group messaging  (WIP) 
Warp 152

Warp 152 - Remove unnecessary wrapper and change group structure

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/examples/ipfs-friends.rs
extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-rg-ipfs/examples/ipfs_messenger.rs
extensions/warp-rg-ipfs/src/lib.rs

This PR allows using the passphrase field in `MultiPass::create_identity` to accept a mnemonic phrase. If one is not provided, a keypair will be generated at random.
WARP-154
This PR also relaxes the need to have tesseract unlocked before initializing warp-mp-ipfs, which would allow it to be unlocked later (which is required for using an existing or creating an identity) on while also allowing warp-rg-ipfs to be initialized without a valid account, but would still require an identity before it actually begin allowing messaging of any kind. 

Reuses passphrase field in MultiPass::create_identity

---

extensions/warp-mp-ipfs/src/store/friends.rs

Fixes friends being erase when dropping internal store.
Resolves #41 

fix/friends: Use std::fs while saving data when dropping store

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-rg-ipfs/examples/messenger.rs
extensions/warp-rg-ipfs/src/store/direct.rs
warp/src/multipass/mod.rs

Changes FriendRequestClosed event to support 2 fields for from and to and change logic so that conversations are properly deleted when receiving such a event
- N/A

refactor: Change FriendRequestClosed to use 2 fields and misc fixes

---

extensions/warp-rg-ipfs/src/store/direct.rs
extensions/warp-rg-ipfs/src/store/mod.rs

Changed/revert the internals to establish a direct conversation topic derived from 2 peer keys. 
Resolves #47 

refactor: Change internals to used a common topic id derived from 2 peers

---

extensions/warp-mp-ipfs/src/store/friends.rs

Removes the additional event bring send when removing a friend
Resolves #53

fix: Remove sending event twice when removing a friend

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/examples/ipfs-friends.rs
extensions/warp-mp-ipfs/examples/ipfs-identity.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/tests/accounts.rs
extensions/warp-rg-ipfs/examples/messenger.rs
warp/src/tesseract/mod.rs

Due to using RwLock/Mutex internally, we dont need to define what is mutable and isnt mutable on the function due to interior mutability.
Resolves #59 

refactor: Remove mut from Tesseract

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/store/friends.rs
warp/src/multipass/mod.rs

Refactors FriendRequestReJected and FriendRequestClosed to be split into 2 incoming and outgoing events and have it broadcast the event on the sender side as well. 
N/A

refactor: Split friend request events

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/document.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/src/store/mod.rs

Moves pictures and banners out of identity by default and store them using unixfs.
Resolves #86 
Although it was tried to minimize any breaking changes, this would require uploading new photos. 

chore/identity: Store pictures in blocks

---

extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-rg-ipfs/Cargo.toml
extensions/warp-rg-ipfs/examples/messenger.rs
extensions/warp-rg-ipfs/src/config.rs
extensions/warp-rg-ipfs/src/lib.rs
extensions/warp-rg-ipfs/src/store/conversation.rs
extensions/warp-rg-ipfs/src/store/direct.rs
extensions/warp-rg-ipfs/src/store/document.rs
extensions/warp-rg-ipfs/src/store/message.rs
extensions/warp-rg-ipfs/src/store/mod.rs

Changes the way messages are stored. Previously, each conversation was stored in its own file. In this PR, it pushes the conversations into the blockstore that can be later resolved by the sender and/or the receipients of the messages of the conversation. 
Resolves #52 
This will require additional testing due to the way conversations are handled to make sure there is little to no chance of a race condition. 
This might get changed to where the cid to each conversation is handled outside of the root ipld depending on the results, however performance under basic test seem to have improved alot.

refactor: Store messages in the blockstore

---

extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-mp-ipfs/src/store/phonebook.rs

Split phonebook future into separate task for each individual to be discovered
Resolves #135 
Event broadcast for online and offline status is disabled by default for now.

refactor: Move phonebook future into separate task

---

extensions/warp-rg-ipfs/examples/messenger.rs
extensions/warp-rg-ipfs/src/config.rs
extensions/warp-rg-ipfs/src/lib.rs
extensions/warp-rg-ipfs/src/store/message.rs

Added flag to disable broadcasting event on the sender side when creating a conversation
N/A
This flag is false by default.

add: flag disable broadcasting `RayGunEventKind::ConversatinCreated` on sender side

---

extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-mp-ipfs/src/store/mod.rs
extensions/warp-mp-ipfs/src/store/queue.rs

Moves the current queue into its own module to handle checking peers in its own task. 
Resolves #146

refactor: Move queue request into its own module

---

extensions/warp-mp-ipfs/Cargo.toml
extensions/warp-mp-ipfs/src/lib.rs
warp/src/multipass/identity.rs

- Convert IdentityUpdate back to an enum
- Add the ability to add a picture or banner from a file (See comments)
- Removes wasm bindgen attr on `IdentityUpdate`
N/A
Adding an image from a file does not validate the image itself at this time. Its suggested that its validated before pushing the image forward. Furthermore, this does not encode the image in base64, which will be done in separate PR
Related to #124 for removal of wasm exports.

refactor: Change IdentityUpdate to enum

---

extensions/warp-mp-ipfs/src/store/document.rs
extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/src/store/mod.rs
extensions/warp-mp-ipfs/src/store/phonebook.rs

- Uses `Vec` instead of `HashSet`
- Reenables verification when fetching `RootDocument`
Resolves #167 

refactor: Use Vec instead of HashSet and reenable verification

---

warp/Cargo.toml
warp/src/crypto/cipher.rs

- Implements functions that uses futures Stream for input and output
- Implements functions that uses futures AsyncRead for input and Stream for output
N/A
- So far there have not been any performance hits when using the async functions for encrypting and decrypting, but should keep an eye on for any blocking of the thread from any task using these functions since encrypting and decrypting can be cpu intensive, however, there is no additional cost.
- If tokio is used, ReaderStream may not be compatible be compatible (requires a bit more investigating). Work around would be to use the compat wrapper for `File` from tokio to make it support futures `AsyncRead`.

add: Implemented Steams for Cipher

---

extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/discovery.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/src/store/mod.rs

Adds a discovery service to be used directly for discovering peers and obtaining their public key
Resolves #160 
Previous implementation was reduce to a single function with no tracking of peers who been discovered, either via a provided namespace or directly over DHT. This implementation will hold a task to get the providers of the namespace and attempt to fetch their public key in a separate task that can be later used to sign, encrypt, and validate any payloads sent over pubsub or check the possible connection status of a discovered peer.

add: Implemented a discovery service

---

extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/src/store/mod.rs

- Switches out to using the payload document directly and transmitting to peers
Relates to #125 (though indirectly since this is more on transmitting than storing) 
This is a breaking change in terms of broadcasting, but would reduce the overall size of the payload in comparison to before

refactor: Transmit data directly rather than using encoding

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/examples/ipfs-identity.rs
extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/tests/accounts.rs
warp/src/multipass/identity.rs

- Add to enum to allow clearing picture, banner, and status from identity
- Remove functions and use enum directly
N/A

refactor: Clear images from identity

---

warp/src/tesseract/mod.rs

- Prevent file from being overridden when setting path by checking if file doesnt exist for tesseract first
N/A

fix: Save when setting only if file doesnt exist

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/lib.rs

- Start with relay first instead of waiting to be notified if node can be publicly access by another peer
- Disable relays when its detected that it can be publicly accessed. 
N/A

refactor: Use relay first

---

extensions/warp-mp-ipfs/Cargo.toml
extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/discovery.rs
extensions/warp-mp-ipfs/src/store/document.rs
extensions/warp-mp-ipfs/src/store/document/identity.rs
extensions/warp-mp-ipfs/src/store/document/utils.rs
extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/src/store/mod.rs
extensions/warp-mp-ipfs/src/store/queue.rs
warp/src/crypto/mod.rs
warp/src/multipass/identity.rs
warp/src/multipass/mod.rs

Previously, we would transmit the identity using `IdentityPayload` to any discovered and connected peers, which would contain data such as images for profile picture and banner, however, this payload would always include/transmit the image when there is an update to eg the username. This caused unnecessary data to be transmitted. This implementation changes the way it is transmitted. Using `IdentityDocument` (which now replaces `IdentityPayload`), it will contain the reference of the images by a cid, which would be compared internally by the cached reference, and if there is a difference, would request for the images to be transmitted and stored in the blockstore, otherwise it would only update the cached reference and transmit an event.
Additional changes:
- …

refactor: Internal changes to transmitting identity

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-rg-ipfs/examples/messenger.rs

Previously, we would connect to relays and make a reservation with all of them, in attempts to create a stable connection with peers over relays, however it would seem that when peers connect doing so with multiple reservation does not allow full connection, causing some data to be loss when being transmitted.
In this PR, it will:
- Connect and use custom relays first, prioritizing them over bootstrap relays
- Use a single relay instead of multiple, except that if a reservation could not be made, to continue through the list
- If any custom relays could not be used to fallback to bootstrap relays, repeating same process.
N/A
It is possible to extend over all addresses of …

chore: Use and prioritize custom relay 

---

extensions/warp-mp-ipfs/src/store/friends.rs
extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-rg-ipfs/tests/group.rs

Previously, we were only mutating the root document by fetching it from the task, adding our changes, and sending it back to be set, however this could lead to some confusion since we would have to mutate the list, store it back to the blockstore, set it on the field before resetting that dag and pinning it. 
In this implementation, it would:
- Move the majority of the mutation of the `RootDocument` to a single task
- Add commands to add/remove single items rather than setting the whole list itself
- Fixes it to only remove the block if the item is not pinned.
N/A
The bug is related to if theres two list with the same item that produce the same cid, it would it would …

chore: Move root document mutation to a single task

---

extensions/warp-mp-ipfs/src/store/identity.rs
extensions/warp-mp-ipfs/tests/accounts.rs
extensions/warp-mp-ipfs/tests/friends.rs
extensions/warp-rg-ipfs/tests/direct.rs
extensions/warp-rg-ipfs/tests/group.rs

- Attempt to extract public key from peer id if it is not apart of `Discovery` and attempt to insert it
N/A
- This should help improve on discovery when receiving an event from a user who is not apart of `Discovery`, however this depends solely on if the public key can be extracted, which should possible due to using ed25519. 
- In the future, we may reject and possibly block the peerid that does not contain an inline public key, or an invalid public key

fix: Attempt public key extraction upon receiving event

---

extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
extensions/warp-mp-ipfs/examples/identity-interface.rs
warp/src/tesseract/mod.rs

- Changes `Tesseract::open_or_create` to support a path and file. 
Resolves #249 (indirectly)
Tesseract, above all, is created first before the extensions is ever initialized. This would cause the keystore to be initialized without actually saving to disk in some cases. This change will not only allow us to create the directory to where the keystore will be located, but also allow better support for multiple keystores in the future (either in the backend, or frontend).

refactor: Split file and directory to keystore

---

extensions/warp-fs-ipfs/Cargo.toml
extensions/warp-fs-ipfs/src/config.rs
extensions/warp-fs-ipfs/src/lib.rs
extensions/warp-fs-ipfs/src/thumbnail.rs

- Added feature to enable webp encoding
- Added `thumbnail_exact_format` to allow outputting thumbnail to format of image. If set to false, it will output to jpeg
N/A 

feat: Minor change to thumbnail generation

---

extensions/warp-blink-wrtc/Cargo.toml
extensions/warp-blink-wrtc/src/host_media/audio/loudness.rs
extensions/warp-blink-wrtc/src/host_media/audio/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/sink/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/source/framer.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/source/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/recorder.rs
extensions/warp-blink-wrtc/src/host_media/audio/speech.rs
extensions/warp-blink-wrtc/src/host_media/mod.rs
extensions/warp-blink-wrtc/src/lib.rs
extensions/warp-blink-wrtc/src/simple_webrtc/mod.rs
tools/audio-codec-cli/Cargo.toml
tools/audio-codec-cli/src/loudness.rs
tools/audio-codec-cli/src/main.rs
tools/blink-webrtc-cli/src/main.rs
warp/src/blink/mod.rs

first of all, apologies for branching an unmerged branch and continuing work on it. It made the # of commits look enormous. 
Created the following modules
- loudness: calculates loudness using root mean square. Is optimized to minimize the number of mathematical operations required. 
- speech: uses the output of `loudness` to determine when to emit an event, indicating that someone is speaking. uses the loudness level and the time since the last event was emitted. 
Modified `audio::SinkTrack` and `audio::SourceTrack`
- the `init` function now receives a channel, used to emit `BlinkEvent`s when someone is speaking. 
- also initialized with the peer's id (a `DID`) which is intended to be used when recording audio. I plan to forward the RTP packets to a thread, and …

feat(blink): emit event when a participant is speaking

---

extensions/warp-mp-ipfs/src/config.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/document.rs
extensions/warp-mp-ipfs/src/store/document/identity.rs
extensions/warp-mp-ipfs/src/store/identity.rs

- Add a configuration option to create a callback function that is called in the event of profile pictures is missing. 
N/A
When a profile picture is missing and there is an available callback, it will execute that function so the implementation can provide a default profile picture. This can be static content or generated content. Note however that this function should not be used for any explicit IO calls.

feat: Add callback in config for default profile picture

---

extensions/warp-fs-ipfs/src/lib.rs

(cherry picked from commit 8a3be76b2c9f640bb791b480750105b1ac31db97)
- Remove the enter context due to compile errors from a tokio update as well as no longer needed (especially after #222 is resolved)
- N/A

chore: Remove enter context

---

extensions/warp-mp-ipfs/examples/identity-interface.rs
extensions/warp-mp-ipfs/src/lib.rs
extensions/warp-mp-ipfs/src/store/document.rs
extensions/warp-mp-ipfs/src/store/document/identity.rs
extensions/warp-mp-ipfs/src/store/identity.rs
warp/src/error.rs
warp/src/multipass/identity.rs
warp/src/multipass/mod.rs

- Introduces `MultiPass::identity_picture` and `MultiPass::identity_banner`
- Removes `Identity::profile_picture` and `Identity::profile_banner`
- Removes unused `Identity::signature` field
- Resolves #268 
While this is an external breaking change, the internals are not broken so there would be no need to migrate images at this time. 
This would reduce the size of the `Identity` since the images would no longer be apart of the object but instead can be fetched from a separate function for the given identity.

refactor: Decouple images from Identity and into trait functions 

---

Cargo.toml
extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/identity.rs
extensions/warp-ipfs/src/store/friends.rs
extensions/warp-ipfs/src/store/identity.rs
warp/src/crypto/keypair.rs
warp/src/multipass/identity.rs
warp/src/multipass/mod.rs

- Implements logic for local importing and exporting identity using mnemonic phrase
- Use `ShortId` in place of slice for the short id
- Split the initialization apart from creating and restoring (this will change again in the future)
- Relates to #43 
- This does not support remote exporting to another node at this time but will come later as this lays out the ground work for manual importing and exporting while internally, it may be done automatically, either at intervals or after each event.
- Exporting does not include messages at this time. This will be done separately as this interface handles the identity, friends list, requests, block list, etc. 
- Does not export internal cache. This …

feat(identity): Local importing and exporting functionality

---

extensions/warp-blink-wrtc/src/host_media/audio/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/sink/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/source/mod.rs
extensions/warp-blink-wrtc/src/host_media/mod.rs
extensions/warp-blink-wrtc/src/lib.rs
tools/audio-codec-cli/src/main.rs
tools/blink-cli/src/main.rs

- calls [play](https://docs.rs/cpal/0.15.2/cpal/traits/trait.StreamTrait.html#tymethod.play) whenever an audio stream is created. Not all platforms play a CPAL stream automatically. `play()` is needed for these cases. 
- changes how audio data is encoded before  being transported over WebRTC. Blink allows the audio I/O devices to have different formats and encodes them to a common format before sending over WebRTC. But that common format wasn't being used - it just so happened that the `audio_source_codec` and `webrtc_codec` default to being the same. But if someone has a 2 channel audio device then the wrong codec was being used to send audio over WebRTC. 
- when an audio device is selected, the `audio_source_codec` and `audio_sink_codec` are now updated to …

fix(audio): make blink audio work on windows and fix audio codecs

---

extensions/warp-blink-wrtc/src/host_media/audio/opus/sink/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/source/mod.rs

- emit AudioDegradation event
- improve call quality during network delay
This PR improves the scenario where network delay causes a large number of audio samples to be decoded and received all at the same time. Previously when this happened, the sound would skip and there would be a large number of random sound bytes. This PR removes said sound bytes. The skipping still happens but that is unavoidable. 
Network delay is detected when the ringbuf in OpusSink overflows. In response, OpusSink drops the incoming samples and all future samples that are received in the next 10ms. Note that each audio frame lasts 10ms (and thus takes 10ms to create).  Anything received within 10ms is assumed to have been affected by the network delay. 
I experimented with using a …

feat(blink): improve call quality during network delays

---

extensions/warp-ipfs/src/behaviour/phonebook.rs
extensions/warp-ipfs/src/behaviour/phonebook/handler.rs

Note: This will change in the future
- Keep connection alive when peer is added to phonebook
- This will change in the future where this behaviour will not prevent timeouts of idle connections

chore: Keep connection alive when set 

---

extensions/warp-ipfs/src/store/conversation.rs
warp/src/raygun/mod.rs

if set, the `limit` will limit the number of messages yielded. This makes it easier to fetch the next X messages when scrolling up/down and makes it possible to fetch X messages before/after a pinned message. 

feat(raygun): use MessageOptions.limit when fetching messages

---

Cargo.toml

The old minimum version of chrono was 0.4 (so 0.4.0 to 0.4.31 which is current).
Raygun has a method, from_naive_utc_and_offset, which was not added to chrono until 0.4.27 https://docs.rs/chrono/0.4.27/chrono/index.html?search=from_naive_utc_and_offset
Setting it to that as the minimum helps with issues if another library has a lower minimum

chore: set minimum chrono version

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/keystore.rs
extensions/warp-ipfs/src/store/message.rs
warp/src/raygun/mod.rs

- Rename `Message::value` to `Message::lines`
- Comment out ffi functions
N/A
- FFI Function that is commented out will get replaced in the future

refactor: Rename value to lines

---

extensions/warp-blink-wrtc/src/host_media/mod.rs
extensions/warp-blink-wrtc/src/lib.rs
extensions/warp-blink-wrtc/src/signaling.rs
tools/blink-repl/src/main.rs
warp/src/blink/call_config.rs
warp/src/blink/mod.rs
warp/src/error.rs

emits signals when the user mutes/unmutes. 
emits signals when the user deafens/undeafens. 
when the user mutes themself, pause the source track. 
when the user deafens, pause the sink tracks, and don't play any newly created tracks. 
adds a `CallConfig` to blink, so the library user can request a struct that tells who is muted/deafened and if the call is being recorded. 
Resolve #347 

feat(blink): emit events when user mutes or deafens themself. 

---

extensions/warp-blink-wrtc/src/host_media/audio/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/sink/mod.rs
extensions/warp-blink-wrtc/src/host_media/audio/opus/source/mod.rs
extensions/warp-blink-wrtc/src/host_media/mod.rs
extensions/warp-blink-wrtc/src/lib.rs
warp/src/blink/mod.rs
warp/src/error.rs

This PR adds new errors to `warp::error:Error`, which are used when blink attempts to build an audio stream for an input or output device. These new error codes will help the UI inform the user why they weren't able to initiate/join a call. 

feat(blink): improve error handling

---

extensions/warp-ipfs/src/behaviour/phonebook.rs
extensions/warp-ipfs/src/behaviour/phonebook/handler.rs
extensions/warp-ipfs/src/lib.rs
tools/relay-server/src/main.rs

- Implements handler to keep a connection alive based on the entry into the behaviour.
- Implements a backoff on emitting an offline event in the event of a connection being reestablished in a short timeframe
- N/A

chore: Keep connection alive

---

extensions/warp-blink-wrtc/src/blink_impl/blink_controller.rs
extensions/warp-blink-wrtc/src/blink_impl/data/mod.rs
warp/src/blink/call_state.rs
warp/src/blink/mod.rs

Currently events are not being emitted when someone mutes/unmutes. This PR will fix that by adding `own_id` to `CallData` with `ParticipantState::default()` when a new call is added to `CallDataMap`. Without this any attempts to update the one's own `ParticipantState` will fail because the update code uses `participants_joined.get_mut()` and participants are otherwise only added in response to `CallSignal::Announce`. 
It also adds a utilty function to `CallData` to eliminate the need for higher layers of the code to use `CallData.participants_joined`. 

fix(blink): initialize CallData with own id

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/identity.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/tests/common.rs

- Split metadata (specifically profile banner and image, platform and status) from `IdentityDocument`
- Introduce a version field to begin creating versions of the structures for important future changes and updates
- Remove `Option` from the timestamp fields 
- N/A
- This is a breaking change, which would require a new identity.
- Since the internal `IdentityDocument` is signed prior to being stored apart of the root document, or sent out to another user, we are had to include all of the metadata when signing the document. This made it harder to exclude specific metadata from the identity document without the owner updating and signing the document. With this change, …

refactor: Split metadata from IdentityDocument

---

extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/conversation.rs
extensions/warp-ipfs/src/store/document/identity.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/files.rs

- Change logic to save data to file prior to removing old previous data. 
- N/A
**Additional comments** 🎤  
- When adding or altering the block store, we would unpin and remove old data prior to saving to disk, however if the application closes before the data is removed, it would then attempt to load invalid data. This was discovered as a chance when uploading multiple files while updating the index. This simple PR solves it by changing the logic to save prior to removing any old data so if the application closes prior to the completion of the old data being removed, it would not affect the new data and would load successfully while the old data can be later cleared.

fix: Save id prior to removing of old data

---

Cargo.toml
extensions/warp-ipfs/src/lib.rs
tools/shuttle/src/main.rs

- Switch bitswap implementation via feature flag
- N/A
- Using a different bitswap implementation would allow for better performance at a cost of internal discovery triggers, although if discovery is disabled, that trigger would not matter.

feat: Use bitswap feature flag

---

Cargo.toml

I previously forked some repositories and then forked them again so that satellite owned them. But I didn't update Warp to use the forks which were owned by satellite. This PR fixes that. No functionality should be changed by this PR. 

chore: update forks related to Blink to use ones owned by satellite

---

extensions/warp-ipfs/src/config.rs
extensions/warp-ipfs/src/store/identity.rs

- Allow a push request for images when announced over mesh
- Removed redundant config flag
- Identities announced over the global topic were originally excluded from any request/response as the requests are generally done over peer specific topics, however with shuttle discovery option enabled, it may cause such request to be excluded, causing any image updates not to be emitted because there is no difference in what was received vs what was pushed after the connection was made between the two or more peers. This PR flip the flag so the request are not excluded while a later change will not exclude it and would attempt to fetch regardless of difference

fix: Dont exclude request when receiving over mesh

---

extensions/warp-ipfs/Cargo.toml
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/document/conversation.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
warp/src/constellation/mod.rs
warp/src/crypto/hash.rs
warp/src/raygun/mod.rs

- Updates the internal messaging events.
- Update the messenger example
- Add field to `ConversationDocument` to mark conversation as deleted, preserving its record internally. 
- Add block  (or restricted) list to `ConversationDocument` for future functionality when a user is blocked/unblocked.

refactor: Update Messaging Events

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/document/conversation.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/tests/group.rs
warp/src/raygun/mod.rs

This adds ability for non-owners to add new members to a group, if owner choose so at creation time. Removal is still only allowed for owner.
The `messenger` cli's `create-group`command is also updated to set this option.
Fixes #386.

feat(groups): Ability to allow anyone to add new members to a group

---

extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/conversation.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/event_subscription.rs
tools/shuttle/src/store/identity.rs
tools/shuttle/src/store/root.rs
warp/src/tesseract/mod.rs

This PR mainly removes racy cleanup code that relies on the value behind `Arc::strong_count` to remain unchanged in the `Drop::drop` impls, which is not a good idea. The docs warn about this:
> Another thread can change the strong count at any time, including
> potentially between calling this method and acting on the result.
In our case, two threads can easily end up dropping the type in question and both `drop` runs thinking that ref count is still 2 and not doing the cleanups.
This PR also:
* Drop manual `Clone` impl of `Tesseract` struct w/ a `derive`.
* Renames `start` methods of task types to `run` as these methods are the task code itself and not just "starting" the task.

fix: Fix racy cleanups

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
warp/src/raygun/mod.rs

Currently, this only means changing of "members can add participants" setting of groups conversation. We only allow owners to change the settings.
This also adds an command in `messenger` example CLI app to turn a group open or closed.
* Fixes #417.

feat(conversation): Allow owners to change conversation settings

---

extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/group.rs

Honor owner's block list when member is added to group.
* Fixes #418.
I haven't managed to test this yet. I wanted to modify the `add_recipient_to_conversation` test to also test this but that one is failing (on my Mac, it's failing 100% of the time) so that (currently) won't work. This should be easy to test though with Uplink (once https://github.com/Satellite-im/Uplink/pull/1725 is in a working shape).

fix(raygun): Honor owner's block list when member is added to group

---

extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/tests/files.rs

- Moves FileStore logic into a separate task
- Change internal logic for `put_buffer`, `get_buffer`, and `sync_ref` to send a future via oneshot.
- Remove hashing due to it taking longer for the stream to complete when dealing with larger files.
- Resolves #435 
- Hashing will be readded later where it will hash a file or data concurrent to the process of storing the data in the local node
- This will be similar to how we generate thumbnails in a blocking thread and yield to the task when fetching it later.
- Even with this change, hashing large data may still take awhile under other conditions like debug profile, etc.

refactor: Move FileStore logic into a separate task

---

warp/src/raygun/mod.rs

- Use serde default attr on group chat settings
- This will cause the fields to use the default values when the fields do not exist when deserializing   
- This will change in the future to be done internally

chore: Set serde default for group settings

---

extensions/warp-ipfs/src/behaviour/phonebook.rs

- Remove panic when channel close
- While we could consider it a bug for the channel to close or drop, if the application closes unexpectedly, it would likely cause it to panic (although not a problem), but in this case we could just break the loop and progress further.

fix: Remove unreachable panic  

---

extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/direct.rs
extensions/warp-ipfs/tests/group.rs

- Use the correct function to delete conversation after receiving event
- Add test for deleted conversation
- While conversation was being deleted when receiving the event, it was not terminating the task handling the pubsub streams since that call was handled from a different function. This PR uses that function instead. 
- Test was added for reassurance

fix: Properly delete conversation when receiving event

---

extensions/warp-ipfs/examples/ipfs-persistent.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/message.rs
warp/src/constellation/mod.rs

- Remove Clone, Serialize and Deserialize from `Progression`
- Use `Error` instead of `Option<String>`

refactor: Use Error directly in Progression::ProgressFailed

---

extensions/warp-ipfs/src/store/document/files.rs

- Change FileDocument reference type from Cid to String
- This changes will help prevent pinning underlining data when walking its graph (related to #469)

refactor: Change file reference type to String

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
tools/shuttle/src/identity/client.rs
tools/shuttle/src/identity/protocol.rs
tools/shuttle/src/identity/server.rs
tools/shuttle/src/server.rs
tools/shuttle/src/store/identity.rs
tools/shuttle/src/subscription_stream.rs

- Pins root document of identity instead of storing a payload
- Previously we would store a encrypted payload blob of the root document, however this may pose as a small problem when expanding into storing messages on the same document since the messages would need to be resolved. Same with the constellation index information. This PR simplifies it by pinning the root document directly, with specific fields containing encrypted blobs directly (eg friends list, request, blocks list), while other fields may only pin down to a specific depth in the graph. 
- Constellation index may only go down to a specific depth per document to prevent pinning the files directly since a …

refactor: Pin root document directly instead of payload

---

extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs

- Remove logic that removes blocks manually
- Removing blocks manually was more of a way to make sure that we cleanup as many blocks as so the local node isnt taking up disk resources, however doing it manually for every update can be costly especially recursively removing a dag of its unpinned blocks, but at the same time, if there are updates to the internal documents, we would want to make sure those blocks are still available when exchanging that info with another peer to pin (eg messages, images, files, etc). So instead of manually removing the blocks, we will only stick with unpinning then and let a later task cleanup those blocks when needed. Blocks removed can be …

chore: Dont remove blocks manually

---

Cargo.toml

We started using a new API in e95df602f.

Bump rust-ipfs to 0.11.4

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/direct.rs
warp/src/raygun/mod.rs

Makes it so the original location is also returned when sending a message with attachments to it. 
The returned stream is now a pair of (optional) Location + Progress

feat: Return location for message attachments

---

extensions/warp-ipfs/src/store/message.rs
warp/src/raygun/mod.rs

- Removes redundant `async_stream::stream` usage
- Replaces `SelectAll` with `StreamMap`
- Resolves #451 

chore: Remove redundant stream macros

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/discovery.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/image_dag.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/src/store/queue.rs
extensions/warp-ipfs/src/store/request.rs
warp/src/crypto/cipher.rs
warp/src/tesseract/mod.rs

- Simplify logic
- Remove migration code from some portions of the stores
- Optimize initialization code
- Reduce allocations 
- It was under the assumption that dyn-clone would reuse allocation from trait objects when cloning, however while investigating some of the allocations, this seem not to be the case when it comes to boxed objects (which shouldve been obvious, but havent looked into it personally until recently). While `warp-ipfs` it uses `Arc` internally (currently and previously), the allocations are still kept low when the trait object is cloned using dyn-clone, however if one wishes to avoid those allocations, it is advised to use `WarpIpfs` directly.

chore: Internal cleanup and optimizations

---

Cargo.toml
extensions/warp-ipfs/Cargo.toml
tools/shuttle/Cargo.toml
tools/shuttle/src/identity.rs
tools/shuttle/src/lib.rs
tools/shuttle/src/main.rs
tools/shuttle/src/message.rs
tools/shuttle/src/store/root.rs
warp/Cargo.toml
warp/src/constellation/file.rs
warp/src/crypto/cipher.rs
warp/src/crypto/hash.rs
warp/src/crypto/multihash.rs
warp/src/tesseract/mod.rs

fixes some of the compilation issues on wasm. 
Package `warp` now compiles, and package `warp-ipfs` almost compiles (1 error left) 
`tools/shuttle` now uses `LocalStorage` instead of `Tokio:fs` when compiled for wasm
#494 (partially)

chore: fix some wasm compilation issues

---

extensions/warp-ipfs/Cargo.toml
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/queue.rs
tools/fs/Cargo.toml
tools/fs/README.md
tools/fs/src/lib.rs
tools/shuttle/src/store/root.rs
warp/src/crypto/cipher.rs

Adds `tools/fs` crate which provides functions to interact with the filesystem in a cross platform way.
In `warp-ipfs` extension, replaces most calls to `tokio::fs::` functions with `tools/fs` equivalent.
#494 (partially)

chore: add wasm compatible fs

---

Cargo.toml
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document/cache.rs
extensions/warp-ipfs/src/store/document/files.rs
extensions/warp-ipfs/src/store/document/root.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/src/store/queue.rs

- Store the queue into the blockstore
- Moves references to the datastore
- Previously, we would store references in corresponding files due to the lacking of the flatfs datastore, however due to the implementation of the flatfs datastore, it would make more sense to move the references there to reduce fs IO calls and make it more uniform without having to check if a path is set to determine if we should write to file or keep it in memory. 
- This should help with #494 since this would push things to the datastore, which may be compatible with wasm.

refactor: Move references into datastore

---

Cargo.toml
extensions/warp-ipfs/Cargo.toml
extensions/warp-ipfs/examples/wasm-ipfs-identity/Cargo.toml
extensions/warp-ipfs/examples/wasm-ipfs-identity/readme.md
extensions/warp-ipfs/examples/wasm-ipfs-identity/src/lib.rs
extensions/warp-ipfs/examples/wasm-ipfs-identity/static/index.html
extensions/warp-ipfs/src/config.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/rt.rs
extensions/warp-ipfs/src/store/event_subscription.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/src/store/queue.rs
extensions/warp-ipfs/src/thumbnail.rs
tools/fs/src/lib.rs
warp/src/constellation/item.rs
warp/src/tesseract/mod.rs

- Adds wasm-bindgen-futures
- Add a `rt` module in `warp-ipfs` to add a alias between spawning tokio and wasm-bindgen task
- Use `web-time` as a drop-in replacement for `std::time::Instant`
- Disable rayon in image due to incompatibility with wasm target
Relates to #494 
- The `rt` module, while it supports spawning a task for tokio or wasm, does not return a handler for wasm side, so it is best to use for task that dont expect to return anything
- Example is added, which is based on `ipfs-identity`, which creates and update the identity. This does not use any networking bits at this time.

chore: Add wasm-bindgen-futures, add example

---

extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/examples/ipfs-friends.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/tests/direct.rs
extensions/warp-ipfs/tests/friends.rs
extensions/warp-ipfs/tests/group.rs
tools/blink-repl/src/main.rs
warp/src/constellation/mod.rs
warp/src/multipass/mod.rs
warp/src/raygun/mod.rs

- Renames `subscribe` function to include the respective trait name to prevent possible conflicts.
- Renames `FriendEvent` to `MultiPassEvent`

refactor: Rename subscribe functions

---

extensions/warp-ipfs/Cargo.toml
extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/examples/ipfs-example.rs
extensions/warp-ipfs/examples/ipfs-friends.rs
extensions/warp-ipfs/examples/ipfs-identity.rs
extensions/warp-ipfs/examples/ipfs-persistent.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/examples/wasm-ipfs-identity/src/lib.rs
extensions/warp-ipfs/src/config.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/tests/accounts.rs
extensions/warp-ipfs/tests/common.rs
tools/blink-repl/src/main.rs
tools/inspect/src/main.rs
warp/src/tesseract/mod.rs

- Remove visibility of `Config` fields and add getters and `_mut` functions
- Remove redundant `Result` from `WarpIpfs::new`
- Export `WarpIpfs`, `Tesseract` and `Config` if target is `wasm32-unknown-unknown`
- Add `WarpIpfsBuilder::into_future` to return `WarpIpfs`
- Relates to #494 
- The `Config` option may be redone to have it fully internal rather than being supported by externally, although this would need to be looked into to determine the best course if we are to also export it to wasm.

refactor: Export WarpIpfs to wasm and remove redundant result

---

Cargo.toml
extensions/warp-ipfs/examples/wasm-ipfs-friends/Cargo.toml
extensions/warp-ipfs/examples/wasm-ipfs-friends/src/lib.rs
extensions/warp-ipfs/examples/wasm-ipfs-friends/static/index.html
extensions/warp-ipfs/src/config.rs
extensions/warp-ipfs/src/store/discovery.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/queue.rs
warp/src/js_exports.rs

- Poll future directly
- Drop task when cancelled or when entry is dropped
- Use `rt::spawn` instead for compatibility between native and wasm.
Relates to #494 

refactor: Poll future, dropping task if entry is dropped or cancelled.

---

warp/src/tesseract/mod.rs

- Add a namespace to tesseract to prevent conflict in `wasm32-unknown-unknown` environment when using localstorage.

feat: Add namespace to wasm variant of tesseract

---

warp/src/tesseract/mod.rs

I ran into an issue where Tesseract.save() on js panics when a key turns out to be None. This prevents save() from panicking when that happens.

chore: fix js tesseract.save() panic on None key

---

extensions/warp-ipfs/src/store/queue.rs

- Wraps bytes into `PayloadMessage` when sending item from queue.

fix: package bytes into PayloadMessage

---

extensions/warp-ipfs/examples/from-js/ipfs-friends.html
extensions/warp-ipfs/examples/from-js/ipfs-identity.html
extensions/warp-ipfs/examples/from-js/ipfs-persistent.html
extensions/warp-ipfs/examples/from-js/ipfs-raygun.html
extensions/warp-ipfs/examples/from-js/tesseract.html
extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/examples/ipfs-example.rs
extensions/warp-ipfs/examples/ipfs-friends.rs
extensions/warp-ipfs/examples/ipfs-identity.rs
extensions/warp-ipfs/examples/ipfs-persistent.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/tests/common.rs
tools/relay-server/src/config.rs
warp/src/js_exports/multipass.rs
warp/src/multipass/mod.rs

- Add `MultiPass::tesseract`
- Support creating/loading tesseract instance if one is not supplied
- This PR will allow one to move away from using any of tesseract loading/creating functions and move it internally if a tesseract instance is not supplied to `WarpIpfs`.
- Additionally, This PR will be used in a later PR that introduces `MultiPass::unlock` and `MultiPass::lock` to allow explicit locking/unlocking.

feat: Add MultiPass::tesseract

---

extensions/warp-ipfs/src/store/identity.rs

Uses the const `MAX_STATUS_LENGTH` instead of `512`. It was already being used everywhere else in `warp-ipfs`, but not in this case. Also, `512` is value of `MAX_STATUS_LENGTH`

chore: Remove unused function

---

warp/src/js_exports/raygun.rs

- Fixes a wrongly named method/name for attachments. Where it was named file but it actually returns the message id

fix(wasm): fix a field and method named wrongly from files to message id

---

extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/examples/ipfs-friends.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/examples/wasm-ipfs-friends/src/lib.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/tests/accounts.rs
tools/inspect/src/main.rs
warp/src/js_exports/multipass.rs
warp/src/multipass/identity.rs
warp/src/multipass/mod.rs

- return stream `GetIdentity` for `MultiPass::get_identity`
- remove async signature
- impl future for `GetIdentity` to return a single `Identity`
- resolves #546
- wasm js export of `MultiPass::get_identity` will continue to mimic the previous design for the time being but may add an additional function to work along side so the stream could be used in js instead (eg when asynchronously loading the list). 
- `GetIdentity` is used instead of `BoxStream` since we are also implementing `Future` for the struct to return a single `Identity` if the `Identifier` isnt a list of public keys, though this may change so so only a single key can be used when awaiting the future so …

refactor: Change MultiPass::get_identity to return a stream

---

extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/direct.rs
warp/src/js_exports/raygun.rs
warp/src/raygun/mod.rs

Adds a size field to `Location::Stream`. And changes the wasm part to also pass in the size with the stream

feature(raygun): add filesize to message attach

---

extensions/warp-ipfs/Cargo.toml
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/direct.rs
extensions/warp-ipfs/tests/files.rs
warp/src/constellation/mod.rs
warp/src/crypto/cipher.rs
warp/src/js_exports/stream.rs
warp/src/raygun/mod.rs

- Change streams of bytes to be handled by `Result<Vec<u8>, std::io::Error>`
- Cleanup streams
- Previously, most streams would be handled either by just bytes representation or may contain a result using warp `Error`. While this may not be a problem now, it could be a problem in the future because converting `Stream<Item = Result<Vec<u8>, _>>` to `Stream<Item = Vec<u8>>` may cause the stream to fail silently, providing data that may not be complete or corrupted, and using warp error for IO streams may be considered redundant. As a result, byte streams will use `Stream<Item = Result<Vec<u8>, std::io::Error>>` to make it more idiomatic, supply error handling and reduce …

refactor: Change most bytes streams to `Stream<Item = std::io::Result<Vec<u8>>>`

---

extensions/warp-ipfs/src/store/identity.rs

- Use `String::contains` when checking supplied username in lookup.
- Previously, we would check if the username matches the exact case, however we should be checking if it contained within the username of the document being evaluated as it previously was done before `MultiPass::get_identity` was converted to a stream.

fix: Use String::contains instead of String::eq

---

extensions/warp-ipfs/src/config.rs

- increases the default storage size limit from 50mb to 2GB in wasm
- increases the default file size limit from 50mb to 100mb

chore(wasm): Increase default size limit for files and storage

---

extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/message.rs
warp/src/raygun/mod.rs

- Use IndexMap for handling reactions in conversations.
- The use of `IndexMap` allows us to preserve the order of insertions so the order of the entries will be preserved across messages where possible.

refactor: Replace {Hash,BTree}Map with IndexMap for reactions

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/utils.rs

- Rename `StreamReader` to `ReaderStream` to properly reflect its functionality. 

chore: Rename StreamReader to ReaderStream

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/src/thumbnail.rs
extensions/warp-ipfs/src/utils.rs
extensions/warp-ipfs/tests/files.rs

- Add basic support for thumbnail generation when uploading via `Constellation::put_stream`
- If a file is more than 20MB, then the thumbnail will not be generated. This may change in the future where we will peak ahead on the headers itself and determine if the thumbnail *could* be generated based on what is supported.
- Instead of duplicating the stream itself and have that polled in a separate task along side the primary stream, we opt for providing the stream of the file after-the-fact and only check the first 20mb. Anymore would disable the generation of the thumbnail to prevent oom for any large files.
- As the other generation methods, this is only for images. …

feat: Generate thumbnail from stream

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/group.rs
warp/src/raygun/mod.rs

- Implement functionality to mark conversations as archived.
- Marking a conversation as archive does not do anything internally besides marking it, but would allow frontend implementations to handle things differently such as ignoring specific events, etc. This may change in the future where specific events are ignored, however this might require the frontend to perform a refresh of the conversation itself.

feat: Implement functionality to [un]archived conversations

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs
extensions/warp-ipfs/tests/direct.rs
warp/src/raygun/mod.rs

- Add `RayGun::set_conversation_description`
- A description length is restricted to 256 characters. 
- In a direct conversation, either participants can set the description while in group conversations, only the creator can set the description.

feat: Add description to conversations

---

Cargo.toml
warp/Cargo.toml
warp/src/js_exports/mod.rs

Adds option to print the warp logs to console on wasm. Requires calling the exported `trace` function so this is not on by default

feat: log to console wasm

---

extensions/warp-ipfs/examples/ipfs-example.rs
extensions/warp-ipfs/examples/wasm-ipfs-storage/src/lib.rs
extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/files.rs
extensions/warp-ipfs/src/store/document/image_dag.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/tests/direct.rs
extensions/warp-ipfs/tests/files.rs
warp/Cargo.toml
warp/src/constellation/directory.rs
warp/src/constellation/file.rs
warp/src/constellation/item.rs
warp/src/constellation/mod.rs
warp/src/js_exports/constellation.rs
warp/src/js_exports/stream.rs
warp/src/multipass/identity.rs
warp/src/raygun/mod.rs

- Use `Bytes` in place of `Vec<u8>` where applicable 
- Using `Bytes` for handling large bytes of data makes it cheaper to handle, reduce allocations and give some additional optimizations, which would reduce memory footprint.
- While we are using `Bytes`, some parts may still resolve to `Vec<u8>`.

refactor: Use `Bytes` in place of `Vec<u8>` where applicable

---

extensions/warp-ipfs/src/store/message.rs

- Reduce duplication when setting/restoring document internal metadata while processing events.

chore: Set document internals first to reduce duplication

---

extensions/warp-ipfs/src/thumbnail.rs

Currently if a gif file is uploaded to constellation it will generate a thumbnail for it normally but this way the thumbnail will only contain one frame of the gif. 
This PR makes it so instead for gifs it will create a proper gif thumbnail too.

feat(files): implement gif thumbnail generator

---

extensions/warp-ipfs/src/store/conversation.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/mod.rs

- Restrict the number of reactions per message.
- Relates to #415
- Each message will have no more than 30 reactions. The number of reactors (ie users) are not limited, however this may change in the future.

chore: Restrict the number of reactions per message

---

extensions/warp-ipfs/src/store/conversation.rs

- Use IndexMap in place of BtreeMap for preserving insertion order 
- relates to #585 
- Currently, we use BTreeMap to handle the sorting of the items inserted into the reference list, however this does not truly preserve the order of insertion into the map as it is determined by key implementation of `Ord`. While this would still be cheaper than `HashMap`, the order is not guaranteed to be preserved in any manner. Instead, we switch to `IndexMap` to rely on the insertion order instead.
- In addition, we make the content id optional in the map so we can preserve the reference list itself when the message is removed to prevent insertion into that list if a slot is …

refactor: Use indexmap to preserve insertion order

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/rt.rs
extensions/warp-ipfs/src/store/discovery.rs
extensions/warp-ipfs/src/store/event_subscription.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/queue.rs
extensions/warp-ipfs/src/thumbnail.rs

- Replace `rt::spawn` with trait to handle spawning task
- Add a `JoinHandle` to return results when awaiting on a value from a task
- While previously, we were able to use `rt::spawn`, which was an alias between `tokio::spawn` on native and `wasm_bindgen_futures::spawn_local` for wasm32, we were not able to await the task for the latter since it does not return an handle. This PR introduces a trait with a basic interface that allows us to implement an executor to be able to spawn a task, with a function `Executor::spawn` returning a `JoinHandle<T>`, with wasm32 having a holder for a oneshot channel that is awaited on if the `JohnHandle` is awaited, or just spawning a …

feat: Replace `rt::spawn` with Executor trait

---

extensions/warp-ipfs/src/store/keystore.rs

- remove redundant field from keystore.

refactor: Remove conversation_id field from keystore

---

extensions/warp-ipfs/examples/identity-interface.rs
extensions/warp-ipfs/examples/ipfs-friends.rs
extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/examples/wasm-ipfs-friends/src/lib.rs
extensions/warp-ipfs/src/store/conversation/message.rs
extensions/warp-ipfs/src/store/document/identity.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message/task.rs
extensions/warp-ipfs/tests/common.rs
extensions/warp-ipfs/tests/group.rs
tools/inspect/src/main.rs
warp/src/multipass/identity.rs
warp/src/raygun/mod.rs

- provide a reference from structs where possible
- This would reduce needless cloning in `Identity`, and other structs, thus reducing allocation where possible
- May still require cloning the data where the content needs to be owned.

refactor: provide a reference from structs where possible

---

extensions/warp-ipfs/examples/messenger.rs
extensions/warp-ipfs/src/store/message/task.rs
extensions/warp-ipfs/tests/direct.rs
extensions/warp-ipfs/tests/group.rs
warp/src/raygun/mod.rs

- Renamed SetGroupName to EditGroupInfo
- Added RemoveParticipants permission. If someone has this they can remove a user from a group
- EditGroupInfo now allows: Renaming group name + description, changing group icon and banner
- Changed no permission error from PublicKeyInvalid to Unauthorized
- Updates the tests which only used direct conversation instead of group

feat: update group permissions

---

extensions/warp-ipfs/src/lib.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/message/community_task.rs
warp/src/raygun/community.rs
warp/src/warp.rs

Adds all the boilerplate for the community messaging methods. Implementations to follow in multiple subsequent PRs. This should keep those PRs smaller and make them easier to review.
The methods are:
- get_community_channel_message
- get_community_channel_messages
- get_community_channel_message_count
- get_community_channel_message_reference
- get_community_channel_message_references
- community_channel_message_status
- send_community_channel_message
- edit_community_channel_message
- reply_to_community_channel_message
- delete_community_channel_message
- pin_community_channel_message
- react_to_community_channel_message
- send_community_channel_messsage_event
- cancel_community_channel_messsage_event
- attach_to_community_channel_message
- …

chore: add boilerplate for community messaging methods

---

extensions/warp-ipfs/src/store/message/community_task.rs
extensions/warp-ipfs/tests/community.rs
warp/src/raygun/community.rs

Implements message attachments for community messages

Feat: community message attachments

---

extensions/warp-ipfs/src/store/event_subscription.rs
extensions/warp-ipfs/src/store/files.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/queue.rs

- replace CancellationToken with AbortableJoinHandle to allow task to abort when dropped.

chore: replace CancellationToken with AbortableJoinHandle

---

extensions/warp-ipfs/src/store/message/attachment.rs

- filter out and ignore message in an attachment if its empty instead of returning an error.

fix: filter out and skip message if empty within attachment

---

extensions/warp-ipfs/src/shuttle/server.rs
extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/message/community_task.rs
extensions/warp-ipfs/src/store/message/task.rs
extensions/warp-ipfs/src/store/payload.rs

- Add recipients to PayloadMessage, which would internally trigger the method to encrypt the message itself.
- Change `PayloadMessage::message` to accept an optional keypair, which would attempt to retrieve the corresponding key and decrypt the message if it is intended for the recipient. 
- Add a function to add a pre-generated encryption key. If one is not supplied, a random key will be created.
- Previously, this container would only contain the message of what was sent, however there may be times where this payload may be intended for specific peers. The original way would be to encrypt the message and send the bytes as apart of the message of the payload, however we …

feat: Add recipients to PayloadMessage

---

extensions/warp-ipfs/src/store/payload.rs

- add a function to obtain a message from a already given encryption key. 
- This function is intended to be used if the peer already know the key to the given message, allowing them to decrypt it without needing to be apart of the recipient list.

feat: add PayloadMessage::message_from_key to decrypt message with a key

---

extensions/warp-ipfs/src/store/identity.rs
extensions/warp-ipfs/src/store/message.rs
extensions/warp-ipfs/src/store/message/community_task.rs
extensions/warp-ipfs/src/store/message/task.rs
extensions/warp-ipfs/src/store/payload.rs
extensions/warp-ipfs/src/store/queue.rs
extensions/warp-ipfs/tests/common.rs

- Use specific type instead of array of bytes in `PayloadMessage` (eg using `PayloadMessage<Message>` instead of `PayloadMessage<Vec<u8>>`)
- Change queue to store the bytes of the payload itself instead of recreating the payload when handling conversation messages.
- Set existing key to payload if exist and available. 
- This does break the internal queue and how messages are sent through the network due to the format change.
- There has been instances where we would send an array of bytes, which were primarily data that were encrypted, however since `PayloadMessage` can internally encrypt the content, it makes no sense to encrypt then build the payload. Now we would …

refactor: use specific types on `PayloadMessage` and send for intended recipient(s)

---

extensions/warp-ipfs/src/store/conversation/message.rs
extensions/warp-ipfs/src/store/conversation/reference.rs
extensions/warp-ipfs/src/store/document.rs
extensions/warp-ipfs/src/store/document/files.rs
extensions/warp-ipfs/src/store/message/attachment.rs
extensions/warp-ipfs/src/store/message/community_task.rs
extensions/warp-ipfs/src/store/message/task.rs
warp/src/raygun/mod.rs

- Add `MessageDocumentBuilder` to be able to build the message document rather than performing redundant conversions
- Remove `MessageDocument::new`
- Add setters, moving additional logic into them to reduce duplication of code.
- Use `IndexSet` in reactions map. 
- Return a `Result` in `MessageDocument::verify`
- Previously, we would build out a `Message` and perform a conversion into `MessageDocument`, but this could be seen as redundant in many cases as we are converting back and forth between the two in different areas when this should not be the case. With this PR, we remove that redundant factor by adding a builder to construct the `MessageDocument` for later use. …

feat: Add MessageDocumentBuilder
