- docs/hooks/overview.md
> chore(typo): fix typo

- .gitmodules
chore(fix): fix 404 on docs page
> chore(fix): fix 404 on docs page

- .github/workflows/fix-typos.yml
> Automatically fix typos

- c/mp_ipfs.c
- c/rg_ipfs.c
- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/examples/ipfs-friends.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-solana/Cargo.toml
- extensions/warp-mp-solana/src/config.rs
- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/config.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- warp/src/crypto/keypair.rs
- warp/src/hooks/mod.rs
- warp/src/lib.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
- warp/src/pocket_dimension/mod.rs
- warp/src/raygun/mod.rs
- warp/src/tesseract/mod.rs
Did some optimizations towards the extensions, exported configurations to FFI and additional functions and changes. 
WARP-145
This PR does introduce a small breaking change in FFI due to the configuration being exported for identity as well as to the backend for identity. 
> WARP-145 - Optimizations 

- .github/workflows/warp_dart_update.yml
Add github workflow to update warp-dart repository on pushes to main branch of Warp
WAPR-130
For this workflow we also need token to access to wapr-dart repo and branch named update-from-wapr there
> add(gh): Add warp_dart_update.yml

- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- warp/src/error.rs
- warp/src/multipass/identity.rs
Add checks so username, status, messages, etc., does not exceed a specific limits as well as checks for the payload that would be used when transmitting it out.
WARP-158
> chore: Add additional checks

- c/Makefile
- c/rg_ipfs.c
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- warp/src/crypto/mod.rs
- warp/src/multipass/identity.rs
Made changes to discovery configuration.
Resolves #25 
This is a bit of a breaking change as it would not be able to discover any peers prior to this commit (since this change uses a put provider towards a specific string). 
> refactor: Changes to discovery

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
Allow one to dial peer through the relay directly due to not being able to utilize DHT for discovery.
Resolves #39 
> feat: Implement Discovery::None

- c/Makefile
- c/mp_ipfs.c
- c/rg_ipfs.c
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- warp/src/multipass/mod.rs
- warp/src/raygun/group.rs
- warp/src/raygun/mod.rs
Introduce a stream of events from MultiPass and Raygun, which would supersede the hooks system.
Resolves #34 
> feat: Implemented Events Interface

- extensions/warp-rg-ipfs/src/store/direct.rs
Performs a soft check on the identity prior to sending a request.
N/A
> chore: Perform a identity check

- extensions/warp-fs-ipfs/examples/ipfs-http-example.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-memory/Cargo.toml
- extensions/warp-fs-memory/examples/fs-memory.rs
- extensions/warp-fs-memory/src/item/directory.rs
- extensions/warp-fs-memory/src/item/file.rs
- extensions/warp-fs-memory/src/item/mod.rs
- extensions/warp-fs-memory/src/native.rs
- extensions/warp-fs-storj/src/s3.rs
- warp/Cargo.toml
- warp/src/constellation/directory.rs
- warp/src/constellation/file.rs
- warp/src/constellation/item.rs
- warp/src/constellation/mod.rs
- warp/warp-derive/src/lib.rs
This would make changes to Constellation to remove references from some trait functions, added `Constellation::rename` as well as changes to `File`, `Directory` and `Item` to introduce initial fields and provide a shared/
Resolves #56 
Resolves #57 
> refactor: Refactor Constellation

- warp/src/tesseract/mod.rs
This would ensure that tesseract isnt truly seen as unlocked unless the function returns true in which case we would mark the corresponding fields true. 
Closes #61 
> chore: Perform a dry-run over the fields when unlocking

- extensions/warp-mp-ipfs/src/lib.rs
Add checks for the profile picture and banner size prior to setting
Resolves #77 
> fix: Add checks for the profile banner and picture

- extensions/warp-rg-ipfs/src/store/direct.rs
Prevent blank messages from sending by trimming whitespaces
N/A
> fix: Trim whitespaces when checking for message length

- warp/src/crypto/mod.rs
Checks and append `did:key:` if it doesnt start with one. 
N/A
> chore: Check and append did:key if it doesnt start with one.

- extensions/warp-fs-ipfs-client/src/lib.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-memory/src/native.rs
- extensions/warp-fs-storj/src/s3.rs
- warp/src/constellation/mod.rs
Removes Constellation::get_path_mut and implements Arc<RwLock<Box<T>>> for Constellation
N/A
> refactor: Remove get_path_mut, implement Arc<RwLock<Box<T>>> for Constellation

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/lib.rs
- warp/src/constellation/file.rs
- warp/src/constellation/item.rs
- warp/src/constellation/mod.rs
Reimplements functions to upload and download with a stream and implement a progression event stream
N/A
This will contain beginning implementations of the events specifically for `put_stream`, however there will be a PR to implement it for other trait functions.
> feat/constellation: Add Constellation::put_stream and Constellation::get_stream

- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
Adds a signature field to RootDocument
N/A
> chore: Added signature to root document

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-pd-stretto/Cargo.toml
- extensions/warp-rg-ipfs/Cargo.toml
Update dependencies
N/A
Do `cargo update`
> fix: Update ipfs dependency

- extensions/warp-fs-ipfs/src/lib.rs
- warp/src/constellation/item.rs
> Refactor: Add duplicate name error renaming item

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- warp/src/raygun/mod.rs
Allow sending events to a conversation. Currently only supported event is MessageEvent::Typing
Resolves #84 
Currently only supported event is MessageEvent::Typing. In the future there may be custom events allowed for frontend usage.
> feat: Send events to conversation

- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
Make changes to the friend request to perform additional checks. This also will make changes to the queue
N/A
> fix/request: Additional checks on incoming request

- extensions/warp-fs-ipfs-client/src/lib.rs
- extensions/warp-fs-ipfs/examples/ipfs-example.rs
- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-memory/src/lib.rs
- extensions/warp-fs-memory/src/native.rs
- extensions/warp-fs-storj/src/s3.rs
- extensions/warp-pd-flatfile/src/lib.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- warp/Cargo.toml
- warp/src/constellation/mod.rs
- warp/src/multipass/mod.rs
- warp/src/pocket_dimension/mod.rs
- warp/src/raygun/mod.rs
Relaxes the use of locks in the current extensions. 
Resolves #99 
> refactor: Relaxes the use of locks

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- warp/src/raygun/mod.rs
Adds additional trait functions to RayGun and other misc changes
Implemented
- RayGun::get_conversation - returns a Conversation
- RayGun::get_message_count - returns the number of messages in a conversation
- RayGun::message_status - returns a status of a message
Resolves #101 (but others are N/A)
> feat: Added additional trait functions

- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/store/direct.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- warp/src/raygun/mod.rs
Adds a modified field to show when a message was last modified
N/A
This only updates the field for when a message text is edited. This doesnt update when pinning or reacting to a message.
> feat: Added modified field to Message

- extensions/warp-rg-ipfs/src/store/message.rs
Splits custom events into its own topic to be sent separately from the messaging events. 
Resolves #105
> refactor: Split events into its own topic

- extensions/warp-pd-flatfile/src/lib.rs
- warp/src/crypto/hash.rs
- warp/src/pocket_dimension/query.rs
- warp/src/raygun/mod.rs
- warp/src/tesseract/ffi.rs
> chore: Linting cleanup

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
Provides platform of user (if enabled in config) as well as extending `IdentityStatus` to provide away, busy status with the ability to set the status through `IdentityInformation::set_identity_status`
Resolves #115 
> feat: Platform and Status Information

- extensions/warp-fs-ipfs/examples/ipfs-example.rs
- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/examples/ipfs-friends.rs
- extensions/warp-mp-ipfs/examples/ipfs-identity.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/tests/accounts.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- warp/src/multipass/mod.rs
This changes the multipass trait to use async, which internally would allow us to remove the block_in_place
Resolves #107 
> refactor: Use async for multipass

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- warp/src/multipass/mod.rs
Cleans up the logic around providing identity status and platform information to allow using one own did to obtain the set status and platform info.
N/A
> chore/multipass: Cleanup logic around platform info and status

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/examples/ipfs-friends.rs
- extensions/warp-rg-ipfs/Cargo.toml
- warp/Cargo.toml
- warp/src/crypto/cipher.rs
- warp/src/crypto/mod.rs
- warp/src/error.rs
- warp/src/lib.rs
- warp/src/multipass/generator.rs
Update and remove unused dependencies
N/A
> chore: Update dependencies

- extensions/warp-fs-ipfs-client/src/lib.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-memory/src/native.rs
- extensions/warp-fs-storj/src/s3.rs
- warp/src/constellation/mod.rs
This trait, along with `ConstellationEventKind`, will be used to send events upon completion of functions outside of the progression event streams for uploading or downloading.
Resolves #122 
> feat: Added ConstellationEvent interface

- extensions/warp-rg-ipfs/src/config.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/message.rs
Load and validate conversation upon loading/fetching it from the block store and start task to allow incoming messages.
N/A
> refactor: Start task on loading valid conversation

- extensions/warp-rg-ipfs/src/store/message.rs
Processes the event in the same task receiving events from the pubsub stream
Resolves #113 
> refactor: Process event in same task

- extensions/warp-rg-ipfs/src/config.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
- extensions/warp-rg-ipfs/src/store/message.rs
Makes passing the recipient list optional and disables it by default 
Resolves #128 
> refactor: Disable storing recipients with message

- extensions/warp-rg-ipfs/src/store/message.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
Uses a specific topic containing the did key instead of a global topic for receiving and handling of conversation-based events
Resolves #126 
> refactor: Use public key style topic

- .github/workflows/fix-typos.yml
- extensions/warp-rg-ipfs/src/store/message.rs
fix typo + add CI to automatically fix typos, same as Uplink
> chore(ci): fix typos + CI to fix typos

- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- warp/src/error.rs
Add a error handle for when one own identity has not been created, loaded or established.
N/A
This can be handy to check for when one own identity has been created before attempting to create one.
> chore: Add error for an nonexisting identity

- extensions/warp-mp-ipfs/src/config.rs
Add recommended profiles for connection limits.
Resolves #68 
This will likely change over time as more testing is done.
> chore: Add profiles for connection limites

- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/tests/accounts.rs
- extensions/warp-mp-ipfs/tests/friends.rs
Adds and update the unit test for warp-mp-ipfs
N/A
> update: Updated mp-ipfs test

- extensions/warp-rg-ipfs/tests/direct.rs
- extensions/warp-rg-ipfs/tests/group.rs
> chore: Added test for rg-ipfs

- extensions/warp-rg-ipfs/src/store/conversation.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- Removes errors from RayGun::get_messages related to empty messages (which would return a empty list instead if there are no messages found)
- Fix conversation not saving upon creation
Resolves #139 
> fix: Remove errors and save conversation on creation

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/examples/ipfs-friends.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
- extensions/warp-mp-ipfs/tests/friends.rs
- extensions/warp-rg-ipfs/tests/direct.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
- Removes FriendRequest (and Friends::list_all_request), and use public keys for incoming and outgoing request function.
- Change how queue is handed
Resolves #142 
> refactor: Remove FriendRequest

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/tests/friends.rs
- warp/src/error.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
- Returns an error if there is an instant response letting the user know if they are blocked when sending a friends request
- Removing outgoing and incoming request when getting a blocked event.
- Fixed it to prevent one from blocking/unblocking their own public key 
Resolves #143 
> feat: Change blocking functionality 

- extensions/warp-mp-ipfs/src/store/identity.rs
Performs a check before unpinning and removing block to compare old block against the current 
N/A
> chore: Check id and remove if there is a difference

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
Cleanup codebase and minor fixes
N/A
> chore: Cleanup 

- extensions/warp-fs-ipfs-client/src/lib.rs
- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- warp/src/constellation/directory.rs
- warp/src/constellation/file.rs
- warp/src/constellation/item.rs
- warp/src/constellation/mod.rs
- warp/src/crypto/cipher.rs
- warp/src/crypto/hash.rs
- warp/src/crypto/keypair.rs
- warp/src/crypto/mod.rs
- warp/src/crypto/multihash.rs
- warp/src/data/mod.rs
- warp/src/hooks/mod.rs
- warp/src/lib.rs
- warp/src/multipass/mod.rs
- warp/src/pocket_dimension/mod.rs
- warp/src/raygun/group.rs
- warp/src/tesseract/mod.rs
Cleans up and ignore clippy warning
N/A
> chore: Cleanup and ignore clippy warnings

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- Update dependencies
- Add config field for portmapping
N/A
Although there is a option to enable port mapping, this is disabled by default. If anything is blocking attempts to utilize this feature (eg firewall, router settings, etc), it will not work, and should fall back to utilizing relay regardless.
> chore: Update dependency and configuration

- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
- warp/src/error.rs
- warp/src/multipass/mod.rs
- Returns bool instead of an empty unit in MultiPass::has_friend
- Cleanup of logic
- Use direct functions for storing photos. 
N/A
> refactor: Cleanup and return bool in MultiPass::has_friend

- extensions/warp-mp-ipfs/examples/ipfs-friends.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/tests/friends.rs
Checks the boolean from the `Result` when using `MultiPass::has_friend` internally 
N/A
> fix: Check the boolean itself

- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-memory/src/native.rs
> fix(Path): Fix path for different platforms

- warp/src/error.rs
- warp/src/tesseract/mod.rs
- Adds `File::sync_all` to `Tesseract::to_file` to ensure that the data reaches the disk
- Switch from `Mutex` to `RwLock` 
- Implemented `Tesseract::open_or_create` and `Tesseract::update_unlock`
N/A
> feat: Changes to Tesseract

- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
Attempts at resolving an issue with invalid signature
N/A
Signature validation will be disabled here for the root document, but will still be checked when signing the document. A separate PR will reintroduce it after additional changes. Reasoning for the invalidation is due to `HashSet` changing the order when the document is fetched.
> fix: Resolve Random Invalid Signature Error

- extensions/warp-mp-ipfs/tests/friends.rs
- extensions/warp-rg-ipfs/tests/group.rs
- Adds test::send_message_in_group_conversation
- Updates test::block_unblock_identity
N/A
> chore/test: Update and cleanup test

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/Cargo.toml
> chore: Update dependency

- extensions/warp-mp-ipfs/src/store/queue.rs
- warp/src/crypto/cipher.rs
- warp/src/tesseract/mod.rs
- Adds `Cipher::self_encrypt_async_read_to_stream` and `Cipher::self_decrypt_async_read_to_stream`
- Removes enum due to it not being used (may get added again in the futures if additional methods are used)
N/A
> chore: Implemented additional functions for Cipher

- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-fs-ipfs/examples/ipfs-example.rs
- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/discovery.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
- extensions/warp-mp-ipfs/src/store/queue.rs
- extensions/warp-rg-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
- extensions/warp-rg-ipfs/src/store/document.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/tests/direct.rs
- extensions/warp-rg-ipfs/tests/group.rs
- Update dependency
- Removes types (which were used to define persistence or temporary) from structs. This makes it so one has to set a path for data to be persistent
N/A
> refactor: Update dependency and remove types from struct

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/tests/direct.rs
- extensions/warp-rg-ipfs/tests/group.rs
- warp/src/raygun/mod.rs
Splits editing functionality out of `RayGun::send` into `RayGun::edit`
Resolves #179 
> refactor: Split editing from RayGun::send into its own function

- extensions/warp-mp-ipfs/src/lib.rs
- warp/Cargo.toml
- warp/src/tesseract/mod.rs
- Adds `TesseractEvent` to `Tesseract`
- Add `Tesseract::subscribe`
Resolves #182 
> feat: Add TesseractEvent

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- warp/src/multipass/identity.rs
- Change `Identifier` to an enum
- Implemented `Identifer::did_keys`
Resolves #185 
> refactor: Change Identifier to enum and implemented Identifier::did_keys

- deprecated/warp-rg-libp2p/src/lib.rs
- deprecated/warp-rg-libp2p/src/solana/groupchat.rs
- extensions/readme.md
- extensions/warp-fs-ipfs/src/config.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
- warp/build.rs
- warp/src/error.rs
- warp/src/raygun/mod.rs
> chore(typos): fix typos

- Cargo.toml
- extensions/warp-fs-ipfs-client/Cargo.toml
- extensions/warp-fs-ipfs/Cargo.toml
- extensions/warp-fs-memory/Cargo.toml
- extensions/warp-fs-storj/Cargo.toml
- extensions/warp-mp-ipfs/Cargo.toml
- extensions/warp-rg-ipfs/Cargo.toml
- warp/Cargo.toml
Uses workspace dependencies
N/A
> chore(cargo): Use workspace dependency

- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/document.rs
- Increase transmit size when transmitting data to another user over pubsub
- Readd logic to lazily get blocks if the root block is not found
This will check the root block against what is stored and not step into the dag for every link, so there is a chance it will attempt to try to request blocks again if they are missing, and will wait until timeout has been reached.
> chore: Increase transmit size

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- warp/src/multipass/mod.rs
- Adds UpdateKind::Misc for any updates not implemented for identity
N/A
> add: Added UpdateKind::Misc

- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/lib.rs
- Adds inline attribute to trait functions
N/A
> chore: Inline functions

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- warp/src/raygun/mod.rs
Adds `Messages` to `RayGun::get_messages` to allow returning messages either as a array, a stream (consisting of existing messages) or in pages.
To select which option to use, `MessageOptions::set_messages_type` would need to be used to set the type to return, otherwise it would default to `Messages::List`
N/A
> feat: Added Messages to RayGun::get_messages

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- warp/src/crypto/keypair.rs
- Add `UpdateEvents` to give option on when events should be emitted 
- Passively push identity out after accepting friend request
- Add flag to save phrase into tesseract
N/A
Would not recommend saving mnemonic phrase but instead leave it be a "one-way path" (not letting it be seen/viewed later) to leave it be secured as much as possible.
> chore: Update configuration for event emitting, and misc

- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/discovery.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
- extensions/warp-mp-ipfs/src/store/queue.rs
- Re-enable emitting online/offline events
- Remove discovery functionality from `PhoneBook`
- Improvements to `Discovery` 
N/A
> chore: Improvements to Discovery and PhoneBook

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- warp/src/raygun/mod.rs
- Refactors `RayGun::attach` to allow an optional message id to attach a file to a reply. 
N/A
> refactor: Allow attaching a file while replying

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/conversation.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/tests/group.rs
- warp/src/raygun/mod.rs
- Adds `RayGun::update_conversation_name`
- Adds `name` field to `RayGun::create_group_conversation`
N/A
Setting a name to a conversation will only work with group conversations.
> chore: Set name to group conversation

- extensions/warp-rg-ipfs/src/store/message.rs
- Enforces conversation name length restrictions
N/A
> fix: Enforce conversation name lengths

- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- tools/inspect/src/main.rs
- Minor cleanup and optimizations
> chore: Small cleanup

- extensions/warp-rg-ipfs/src/store/message.rs
- Saves id after creating conversation
N/A
This issue is noticable only if loading a conversation without sending message or updating the conversation.
> fix: Save conversation after creating

- extensions/warp-rg-ipfs/examples/messenger.rs
- extensions/warp-rg-ipfs/src/lib.rs
- extensions/warp-rg-ipfs/src/store/message.rs
- warp/src/raygun/mod.rs
- Adds and passthrough `Location` to `RayGun::attach`
N/A
> chore: Add `Location` to `RayGun::attach` 

- extensions/warp-mp-ipfs/tests/accounts.rs
- extensions/warp-mp-ipfs/tests/common.rs
- extensions/warp-mp-ipfs/tests/friends.rs
- extensions/warp-rg-ipfs/tests/common.rs
- extensions/warp-rg-ipfs/tests/direct.rs
- extensions/warp-rg-ipfs/tests/group.rs
- Performs internal mesh connections instead of attempting external connections or connections via mdns
- use a common module for specific functions
N/A
Some test will error out at the moment, but will be looked more into in a separate PR (specifically the blocking/unblocking) to resolve the issue
> chore: Internal connection in test

- extensions/warp-rg-ipfs/src/store/message.rs
- extensions/warp-rg-ipfs/tests/group.rs
- Allows an empty group name to be set
- Update test to factor additional group chat functions
N/A
> chore: Allow an empty group name to be set

- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/mod.rs
- extensions/warp-rg-ipfs/src/store/mod.rs
- Cleans up codebase, removing or correcting deprecated functions
N/A
> chore: Remove/cleanup deprecated functions

- extensions/warp-mp-ipfs/src/store/mod.rs
- Extracts public key from peer id if key is inline
Resolves #235 
> chore: Implement PeerIdExt

- extensions/warp-mp-ipfs/src/config.rs
- Update default relay list
N/A
> chore: Update relay list

- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/queue.rs
- Removes the last bit of the old model for sending/receiving data
N/A
After this PR, there may (but no guarantee) be a prehook implemented to allow for any previous implementations to send/receive using the old model.
> refactor: Remove remnants of old data model

- extensions/warp-fs-ipfs/src/lib.rs
- warp/src/constellation/directory.rs
- warp/src/constellation/file.rs
- Adds and enforces name limits on File and Directory
Resolves #240 
> chore: Add and enforce limits on name

- extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
- extensions/warp-fs-ipfs/src/config.rs
- extensions/warp-fs-ipfs/src/lib.rs
- extensions/warp-fs-ipfs/src/thumbnail.rs
- extensions/warp-fs-ipfs/src/utils.rs
- warp/src/constellation/directory.rs
- warp/src/constellation/file.rs
- warp/src/constellation/item.rs
- Adds FormatType to determine thumbnail format. 
N/A
> feat: Added FormatType

- extensions/warp-fs-ipfs/src/thumbnail.rs
- Dont change dimensions of an image if its less than the configured account
N/A
> fix: Compare image dimension to the dimension parameters

- extensions/warp-mp-ipfs/examples/identity-interface.rs
- extensions/warp-mp-ipfs/src/config.rs
- extensions/warp-mp-ipfs/src/lib.rs
- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- extensions/warp-mp-ipfs/src/store/queue.rs
- extensions/warp-rg-ipfs/examples/messenger.rs
- Add a configuration option to choose to use bitswap or pubsub when transporting data. 
N/A
> chore: Implement option to transport data

- extensions/warp-mp-ipfs/src/store/friends.rs
- extensions/warp-mp-ipfs/src/store/identity.rs
- Push the broadcast sender behind a single function
N/A
This will make it cleaner to change how we send off events to stream in the future in the event of any changes.
> chore: Cleanup event emitting 

- extensions/warp-rg-ipfs/src/store/message.rs
- Store streams into a single list and poll the list for yielding `AttachmentKind` events
- Resolves #274 
> chore: Store streams into list

- extensions/warp-mp-ipfs/src/behaviour/phonebook.rs
- extensions/warp-mp-ipfs/src/store/phonebook.rs
> chore: Minor cleanup in phonebook

- warp/src/multipass/mod.rs
- Adds `MultiPass::import_identity` to the interface
This method is not implemented directly into any extensions at this time but will be implemented at a later point 
> feat: Implement MultiPass::import_identity

- Cargo.toml
- extensions/warp-blink-wrtc/Cargo.toml
- tools/audio-codec-cli/Cargo.toml
…r libopus
a previous PR which included a Dockerfile with instructions for building Warp for mobile also included modifications to the opus-rs crate. These modifications worked when libopus was being built from source and statically linked but did not work when linking to the library dynamically. This PR fixes that. 
> fix(blink): make opus compile correctly

- extensions/warp-blink-wrtc/src/host_media/audio/mod.rs
- extensions/warp-blink-wrtc/src/host_media/audio/opus/sink/mod.rs
- extensions/warp-blink-wrtc/src/host_media/mod.rs
- extensions/warp-blink-wrtc/src/lib.rs
- tools/blink-webrtc-cli/src/main.rs
- warp/src/blink/mod.rs
adds a function to multiply a peer's audio by a constant. This has the effect of making them sound quieter or louder. 
partially addresses #271 
> feat(blink): add volume control

- Cargo.toml
one of the opus related crates failed to build with windows due to my modifications. the dependency has been fixed and updated. 
> fix(windows): make blink build for windows

- extensions/warp-ipfs/src/lib.rs
- Uses ipfs handle directly when importing index
N/A
> fix: Use ipfs directly during initialization

- extensions/warp-ipfs/src/lib.rs
- Store the ipfs handle after initializing identity and friend store 
N/A
> fix: store ipfs after identity and friends store

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/files.rs
- extensions/warp-ipfs/src/store/mod.rs
- Moves constellation logic into its own module
N/A
This move will allow easier change of the initialization functions in the near future and cleanup the main module a bit.
> refactor: Move logic into its own module

- Cargo.toml
- extensions/warp-ipfs/examples/ipfs-identity.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/tests/common.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
- Implements IdentityProfile 
- Refactors `MultiPass::create_identity` to return `IdentityProfile`. 
Resolves #306 
> refactor: Implement IdentityProfile

- extensions/warp-fs-memory/src/lib.rs
- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/ipfs-persistent.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-pd-flatfile/src/lib.rs
- extensions/warp-pd-memory/src/lib.rs
- tools/audio-codec-cli/src/main.rs
- tools/inspect/src/main.rs
- warp/src/constellation/directory.rs
- warp/src/constellation/item.rs
- warp/src/constellation/mod.rs
- warp/src/multipass/identity.rs
- warp/src/pocket_dimension/query.rs
- warp/src/tesseract/ffi.rs
- warp/src/tesseract/mod.rs
> chore: Cleanup clippy warnings

- extensions/warp-ipfs/src/store/message.rs
- Yield error when attachments are empty
> chore: Yield error if there are no files attached

- tools/blink-cli/src/main.rs
sometimes testing the `blink-cli` is hampered by not being able to discover each other. `Multipass` has a built in discovery mechanism. This PR attempts to make use of that by auto-friending anyone dialed using the `blink-cli`. 
> fix(blink): auto friend peers to aid in discovery

- extensions/warp-ipfs/examples/ipfs-persistent.rs
- extensions/warp-ipfs/src/store/files.rs
- warp/src/constellation/directory.rs
- warp/src/constellation/file.rs
- warp/src/constellation/item.rs
- Implements `Item::path` and `Item::set_path`
- Implements `Directory::rebuild_paths`
N/A
> feat: Implement path, set_path and rebuild_paths functions

- Dockerfile.aarch64-android
Fixes the docker file to pull the latest `cargo-mobile2` crate
We have recently renamed `tauri-mobile` project to `cargo-mobile2` for SEO reasons.
> chore: `tauri-mobile` -> `cargo-mobile2`

- extensions/warp-ipfs/src/store/message.rs
- Remove logic renaming incoming attachments
- Change logic to download without using constellation api
- Remove code that stores reference in constellation
N/A
- For the time being this will remove the logic that stores the file reference in constellation, but will be readded in the near future
> refactor: Dont download attachment using constellation api

- extensions/warp-ipfs/src/store/keystore.rs
- extensions/warp-ipfs/src/store/message.rs
- Reduce spawned task
- Minor cleanup and reorganization
N/A
> chore: Cleanup messaging

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/message.rs
- warp/src/raygun/mod.rs
- Implements timestamp to `Conversation`
- Updates `Conversation::modified` when there is an update to the messages
- Resolves #329
> chore: Implement conversation timestamp

- extensions/warp-ipfs/src/lib.rs
- Simplify lookup logic
- Remove spawned task while connecting to relay
- N/A
> chore: Minor changes to initialization and lookup

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/src/behaviour/phonebook.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/tests/group.rs
- tools/relay-server/Cargo.toml
- tools/relay-server/src/config.rs
- tools/relay-server/src/main.rs
- warp/src/multipass/mod.rs
- added tool/relay-server
- Cleanup example, ignoring bootstrap if discovery is disabled.
- N/A
> chore: Added additional tool and cleanup

- warp/src/blink/call_state.rs
Uplink needs these implemented to use `CallState` in the `Props` of a dioxus  `Element`. 
> fix(blink): implement Eq and PartialEq for CallState

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/message.rs
- tools/relay-server/src/main.rs
- warp/src/raygun/mod.rs
> feat: Implement message references

- README.md
> chore(docs): minor suggestions

- Cargo.toml
- extensions/warp-ipfs/Cargo.toml
- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/ipfs-persistent.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- warp/src/constellation/mod.rs
- warp/src/multipass/mod.rs
- warp/src/raygun/mod.rs
- Implement `Stream` instead of dereferencing  
- Cleanup redundant configuration
- Change logic to disable kademlia protocol if discovery is disabled
- Update examples
-N/A 
> chore: Remove redundant config and cleanup

- extensions/warp-ipfs/src/store/identity.rs
- Implements a signed request and versioning for the request
- This implementation attempts to maintains compatibility with older request, which would be unsigned, however those request may not have support in the future. 
- In a past implementation, friend requests were signed, however due to the nature of the internal implementations and the changes made, the object was simplified. Now, in this PR, it introduces the signatures back while we pass the request off to other peers or nodes for routing purposes, while maintaining compatibility with unsigned request from previous implementation
> feat: implement signed requests

- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/document.rs
- extensions/warp-ipfs/src/store/document/conversation.rs
- extensions/warp-ipfs/src/store/document/identity.rs
- extensions/warp-ipfs/src/store/document/image_dag.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/files.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/mod.rs
- tools/relay-server/src/main.rs
- warp/src/error.rs
- Simplify functionality
- Use conversion to simplify function calls
- Expand logging 
- Remove blocks recursively
- N/A
> chore: Minor Cleanup

- README.md
Add Linux dependencies & fix formatting. The dependencies added are taken from the CI action so they're likely not exhaustive. Also broke very long lines so improved readability.
> chore(readme): Add Linux dependencies & fix formatting

- extensions/warp-blink-wrtc/src/host_media/mod.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/store/discovery.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/mod.rs
- extensions/warp-ipfs/src/store/phonebook.rs
- extensions/warp-ipfs/src/store/request.rs
- warp/src/constellation/file.rs
- Adds or make use of the request timestamp for incoming/outgoing friend request
- Expands utility traits
- Added a new payload utility for future events
- Add placeholder for announcing identity
- N/A
> feat: Added timestamp to incoming/outgoing request

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/discovery.rs
- extensions/warp-ipfs/src/store/document.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/files.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/tests/accounts.rs
- tools/shuttle/src/identity/client.rs
- Slight cleanup and optimizations 
- Added span as a placeholder in multiple components
- Slight improvement on discovery
> chore: Minor cleanup and optimization 

- extensions/warp-ipfs/examples/ipfs-friends.rs
> chore: Update example

- extensions/warp-ipfs/src/store/identity.rs
- Exports root document after registration
- N/A
> fix: Export root document after registration

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/store/conversation.rs
- warp/src/raygun/mod.rs
Refactoring and cleanup to make `messenger` more maintainable.
> chore(messenger): A few commits to cleanup the code

- tools/relay-server/Cargo.toml
- tools/relay-server/src/config.rs
- tools/relay-server/src/main.rs
- Add a new flag to point to a configuration file
- Increase relay parameters
- N/A
> chore: Update relay configuration

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/messenger.rs
- Cleanup linting
- Change flags in example
> chore: Change flags in example and minor cleanup

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/src/store/document/cache.rs
- Change and cleanup pinning logic in identity cache
- Added test
> chore: Change logic in cache

- extensions/warp-ipfs/examples/messenger.rs
List all commands in help message. Also make it so that future commands are always added with their help reference included.
> fix(messenger): List all commands in help message

- .github/workflows/cargo-test.yml
Change the GH action to run all tests, not just ones in `warp` package.
> fix(ci): Run all tests

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/tests/direct.rs
- warp/src/raygun/mod.rs
- Remove `Reaction`, switching it to `BTreeMap`
> refactor: Use a map for reactions

- warp/src/tesseract/mod.rs
- Update tesseract test to make sure it locks after the final drop
> chore: Update tesseract test

- warp/src/raygun/mod.rs
Add missing Default impl for ConversationSettings.
> fix: Add missing Default impl for ConversationSettings

- warp/src/lib.rs
- Remove functions leftover that were used for calling async functions in ffi
> chore: Remove unused async function and global runtime

- extensions/warp-fs-memory/src/native.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/files.rs
- warp/src/constellation/mod.rs
- Return a progress stream for `Constellation::get`
> refactor: Return a stream for `Constellation::get`

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/identity.rs
- tools/shuttle/src/identity/client.rs
- Move to using a vector instead of a map for storing addresses
> refactor: Switch to using a vector instead of a map

- warp/src/constellation/directory.rs
- implements `Directory::get_last_directory_from_path` to obtain the last directory from a valid path
- Minor optimization
> feat: Add Directory::get_last_directory_from_path and optimize code

- extensions/warp-ipfs/src/store/files.rs
- Store files with a define path in the correct directory so the file is not named the path.
- Check for path and if one doesnt exist, use current path, otherwise grab the directory from the index for the valid path
- This changes the internal logic to either use the current path if one isnt used for local storage, or grab the directory starting from root (assuming its valid). This means that one can use `file.txt`, which would get stored in the current directory that was either default (which is root by default) or set via `Constellation::select`, or `/my/path/file.txt` to get stored in `/my/path` (if the directories exist).
> fix: Store files in defined directories

- extensions/warp-ipfs/tests/accounts.rs
- extensions/warp-ipfs/tests/common.rs
- extensions/warp-ipfs/tests/direct.rs
- extensions/warp-ipfs/tests/files.rs
- extensions/warp-ipfs/tests/friends.rs
- extensions/warp-ipfs/tests/group.rs
- Adds tests for constellation
- Add test for sending attachment
> chore: Add files test

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/tests/direct.rs
- warp/src/raygun/mod.rs
- Adds `RayGun::download_stream` to download attachment using a stream
- Update test
> feat: Add RayGun::download_stream

- extensions/warp-ipfs/src/store/files.rs
- Add missing channel to trigger export after a file has uploaded prior to emitting event
- N/A
- While an export is trigger when the guard is dropped, that export is done lazily at the end of the stream, which may not complete if the application close right after the stream ends or if one decides to exit the application after `Progression::ProgressComplete`. #445 originally was suppose to have this implemented but was missing and not caught during testing. This PR adds it back in to signal back to the task to trigger an export if a file completes so the index can be up-to-date so when everything is initialized again, the index would be up to date.
> fix: Add missing channel to trigger an export after uploading

- .cargo/config.toml
Same as https://github.com/Satellite-im/Uplink/pull/1872 but for Warp, instead of Uplink.
> chore(debug): Don't link debug info for dev profile

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/tests/direct.rs
- warp/src/raygun/mod.rs
Returns a uuid for a message with attachment together with the upload stream
> feat: return uuid together with attachment stream

- extensions/warp-ipfs/examples/messenger.rs
- Use a stream map to handle conversation stream events instead of individual tasks
- Remove lock around `topic` variable
> chore: Cleanup messaging example

- tools/shuttle/src/server.rs
- tools/shuttle/src/store/identity.rs
- tools/shuttle/src/store/root.rs
- tools/shuttle/src/subscription_stream.rs
- Remove calls to remove blocks manually
- Set relay configuration to max
- Cleanup logging
- Return stream of identities instead of a list
> chore: Cleanup shuttle inner logic

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/document.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/identity.rs
- Encrypts most of the data in the root document
- Rename `ExtractedRootDocument` to `ResolvedRootDocument`
- This PR is in prep of pinning the root document directly on shuttle instead of storing a payload reference of it
> refactor: Encrypt most of the data in the root document

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/message.rs
- Move conversation list to root document
> chore: Store conversations in root document

- Cargo.toml
- extensions/warp-ipfs/Cargo.toml
- extensions/warp-ipfs/src/behaviour/phonebook.rs
- tools/relay-server/Cargo.toml
- tools/shuttle/Cargo.toml
- warp/Cargo.toml
- warp/src/crypto/mod.rs
Drop unneeded dependencies. In some cases the only use of a crate is replaced by the same/similar API from another crate we already depend on.
> chore: Drop unneeded dependencies

- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/mod.rs
- Make identity announcement topic global
> chore: Make announcement topic a global variable

- Cargo.toml
- extensions/warp-ipfs/Cargo.toml
- tools/audio-codec-repl/Cargo.toml
- tools/blink-repl/Cargo.toml
- tools/inspect/Cargo.toml
- tools/relay-server/Cargo.toml
- tools/shuttle/Cargo.toml
- tools/video-codec-cli/Cargo.toml
- warp/Cargo.toml
- Use specific features from crates
> chore: Cleanup dependencies

- README.md
Adds build requirements for macOS to the readme
partially: https://github.com/Satellite-im/Warp/issues/46
(this PR only adds the requirements for macOS)
> chore: add macOS build requirements to readme

- warp/Cargo.toml
> chore: Remove send_guard feature

- docs/runes-quickstart.md
> chore(docs): add hugo docs

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/document/files.rs
- extensions/warp-ipfs/src/store/document/identity.rs
- extensions/warp-ipfs/src/store/document/image_dag.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/mod.rs
- Define global variables that set specific lengths
- Some variables that arent used currently, will be used in the future.
> chore: Set variables with defined length

- Cargo.toml
- extensions/warp-ipfs/Cargo.toml
- extensions/warp-ipfs/src/js_exports.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/message.rs
- tools/wasm-example/www/index.html
- tools/wasm-example/www/ipfs-identity.html
- warp/Cargo.toml
- warp/src/js_exports.rs
- warp/src/lib.rs
- warp/src/multipass/generator.rs
- warp/src/multipass/identity.rs
exports MultiPass to js
Includes an ipfs-identity from js example
#494 (partially)
> export ipfs-identity-to-js

- Cargo.toml
- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/document.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/request.rs
- extensions/warp-ipfs/tests/common.rs
- tools/blink-repl/src/main.rs
- tools/inspect/src/main.rs
- tools/relay-server/src/main.rs
- Refactor configuration to remove unused options and simplify logic
> chore: Configuration cleanup

- warp/src/tesseract/mod.rs
- Use a single lock within tesseract
> refactor: Use a single lock within Tesseract

- .github/workflows/cargo-test.yml
> chore: Disable logging in CI

- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/lib.rs
- Add configuration option to enable persistence
- Uncomment code to enable persistence for wasm
> chore: Enable persistence for wasm

- extensions/warp-ipfs/src/config.rs
- Adds Config::minimal_with_relay
> feat: Add Config::minimal_with_relay

- warp/src/js_exports/constellation.rs
- warp/src/js_exports/raygun.rs
Added functions that were missing for js.
Reordered js functions to be in the same order as in the trait so that it's easier to see if any are missing.
Related to: #494
> chore: export missing js functions

- warp/src/constellation/item.rs
- warp/src/js_exports/constellation.rs
Adds missing methods to js constellation's `Item` struct
Related to #494
> chore: add missing methods to js constellation Item struct

- extensions/warp-ipfs/src/lib.rs
- Disable webrtc transport temporarily
> chore: Temporarily disable webrtc transport

- extensions/warp-blink-wrtc/src/blink_impl/mod.rs
- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/ipfs-friends.rs
- extensions/warp-ipfs/examples/ipfs-identity.rs
- extensions/warp-ipfs/examples/ipfs-persistent.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/examples/wasm-ipfs-friends/src/lib.rs
- extensions/warp-ipfs/examples/wasm-ipfs-identity/src/lib.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/tests/accounts.rs
- tools/blink-repl/src/main.rs
- tools/inspect/src/main.rs
- warp/src/js_exports/multipass.rs
- warp/src/multipass/identity.rs
- warp/src/multipass/mod.rs
- Rename MultiPass::get_own_identity to MultiPass::identity
- Add MultiPass::profile_picture and MultiPass::profile_banner to reference to the local identity images.
- Remove Identifier::own and its variants.
- resolves #547 
> chore: Add MultiPass::{identity,profile_{picture,banner}}

- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/tests/direct.rs
- warp/src/raygun/mod.rs
- Add `Location::Stream` to supply a stream
- Add `LocationKind` to replace `Location` in `AttachmentKind`
- relates to #494 
> feat: Add Location::Stream and LocationKind

- extensions/warp-ipfs/src/config.rs
- change default relay for wasm32 target
> chore: Update relay

- warp/src/js_exports/multipass.rs
- warp/src/multipass/identity.rs
- exposes functions from the IdentityInformation trait to js
> chore: add missing identity info js functions

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/discovery.rs
- extensions/warp-ipfs/src/store/document/files.rs
- extensions/warp-ipfs/src/store/files.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/thumbnail.rs
- warp/src/crypto/keypair.rs
- Removes redundant result from FileStore::new
- Cleanup code
> chore: Remove redundant result and minor cleanup

- warp/src/tesseract/mod.rs
> fix: update keycheck docs

- warp/src/js_exports/raygun.rs
- Adds more stricter typing to `list_conversation` and `fetch_messages`:
- `list_conversation` returns now a `ConversationList` which holds an array of `raygun::Conversation`. `convs` then maps and returns the conversations as a wasm `Conversation`.
- There is not really a way to do this for `fetch_messages` as that returns multiple types of data. Instead i added a static function `message_from` that can turn a Json Object of `raygun::Message` into a wasm `Message` so something like following is possible:
> feat(wasm): Add more stricter raygun typing

- Cargo.toml
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/document/cache.rs
- extensions/warp-ipfs/src/store/files.rs
- extensions/warp-ipfs/src/thumbnail.rs
- Borrow public key instead of owning it.
- Perform checks to stream total size
- Update image dependency
> chore: Misc cleanup and size check to Constellation::put_stream

- extensions/warp-ipfs/src/thumbnail.rs
- Remove redundant webp feature check.
> chore: Remove feature check

- extensions/warp-ipfs/examples/from-js/index.html
- extensions/warp-ipfs/examples/from-js/ipfs-identity-metadata.html
- warp/src/js_exports/multipass.rs
- Fixes AddMetadataKey and RemoveMetadataKey missing from js identity update enum
- Adds a js example for identity metadata usage.
> chore: add js enum variants for updating identity metadata

- tools/relay-server/src/main.rs
- Support external addresses in relay to determine how the node can be reached if they are explicitly defined. 
- Previously we would use all listeners as external addresses, however some nodes may use local and private addresses that may not be reachable to the public. This PR introduce a flag that would allow one to explicitly define the address where the relay can be reached. This would reduce the number of addresses provided and allow us to explicitly use dns addresses when available.
> feat Support external addresses in relay-server

- extensions/warp-ipfs/src/store/identity.rs
- Report correct error when getting identity banner
> fix: Report correct error

- extensions/warp-ipfs/tests/accounts.rs
- extensions/warp-ipfs/tests/common.rs
- extensions/warp-ipfs/tests/direct.rs
- extensions/warp-ipfs/tests/files.rs
- extensions/warp-ipfs/tests/friends.rs
- extensions/warp-ipfs/tests/group.rs
> chore: Cleanup test

- extensions/warp-ipfs/src/store/message.rs
- removes redundant mutable reference.
> chore: Remove redundant mutable reference

- warp/src/js_exports/raygun.rs
Fixes the problem of attachment thumbnails missing by writing each file to js individually
> fix(wasm): fix attachments having no thumbnail

- extensions/warp-ipfs/src/config.rs
Exposes some functions to allow modifying the config during init
> feat(wasm): expose some config functions to wasm

- extensions/warp-ipfs/src/store/files.rs
- warp/src/constellation/item.rs
- warp/src/error.rs
- Implement recursive removal of files and directories when calling `Constellation::remove` with `recursive` being true
- If flag is set to false, it will only remove a single file or an empty directory
> feat: Implement recursive removal

- warp/src/raygun/mod.rs
- Add GroupSettings::new.
- Add constructor to `GroupSettings::new`
> feat: Add GroupSettings::new

- extensions/warp-ipfs/src/store/files.rs
Fixes recursive deletion not deleting the folder itself
> fix(constellation): remove target directory after recursive removal

- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/document/root.rs
- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/mod.rs
- extensions/warp-ipfs/tests/direct.rs
- warp/src/raygun/mod.rs
- Add support for icons and banners in conversations.
- Currently, there is no specific dimensions limit to the icons or banners, but only an explicit size limit which is 4MB for icons and 8MB for banners.
> feat: Add icons and banners for conversations

- Cargo.toml
- update dependency
- fixes an error when running in the browser
> fix: update dependency

- extensions/warp-ipfs/src/store/message.rs
- remove redundant calls to get conversation document
> chore: remove redundant calls to get conversation document

- extensions/warp-ipfs/src/store/conversation.rs
- Get message document from reference list instead of the list of messages.
> chore: get message document directly from reference list

- extensions/warp-ipfs/src/store/message/task.rs
- queue previous pending messages received before the key exchange was performed.
> fix: queue previous pending messages

- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/message/task.rs
- move discovery entries into conversation task
> chore: move discovery into conversation task

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/src/config.rs
- extensions/warp-ipfs/src/store/identity.rs
- extensions/warp-ipfs/tests/common.rs
- add check for `Platform::Web` and remove configuration option to share platform to share by default.
> refactor: Add check for Platform::Web and remove configuration option

- extensions/warp-ipfs/src/rt.rs
- moves the joinhandle enum into a struct to prevent direct access to the handles.
> chore: move enum handle into a struct

- extensions/warp-ipfs/tests/community.rs
Makes community tests wait for `RayGunEventKind::CommunityInvite` event before accepting invites. This should solve the flaky tests that sometimes fail in the ci.
> chore: fix tests for ci

- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/mod.rs
- extensions/warp-ipfs/tests/community.rs
- warp/src/raygun/mod.rs
> Feat: delete community

- extensions/warp-ipfs/src/store/message.rs
- extensions/warp-ipfs/src/store/message/attachment.rs
- extensions/warp-ipfs/src/store/message/task.rs
- extensions/warp-ipfs/tests/community.rs
- move attachment logic into its own stream impl
- This is a partial start to allow shared logic and functionality, possibly reducing redundant and duplication of code.
> chore: Add attachment stream

- extensions/warp-ipfs/src/lib.rs
- extensions/warp-ipfs/src/store/conversation.rs
- extensions/warp-ipfs/src/store/identity.rs
- remove redundant create_dir calls
- cleanup imports and function logic
> chore: misc cleanup

- extensions/warp-ipfs/examples/identity-interface.rs
- extensions/warp-ipfs/examples/ipfs-friends.rs
- extensions/warp-ipfs/examples/messenger.rs
- extensions/warp-ipfs/tests/accounts.rs
- extensions/warp-ipfs/tests/direct.rs
- extensions/warp-ipfs/tests/files.rs
- extensions/warp-ipfs/tests/group.rs
> chore: cleanup linting

- extensions/warp-ipfs/src/store/community.rs
- extensions/warp-ipfs/src/store/message/community_task.rs
- extensions/warp-ipfs/src/store/mod.rs
- extensions/warp-ipfs/tests/community.rs
- warp/src/raygun/mod.rs
Implements community icon and banner
> feat: community icon and banner

- extensions/warp-ipfs/shuttle/src/main.rs
- extensions/warp-ipfs/src/shuttle/server.rs
- Add options to configure and enable GC instead of having it enabled by default in shuttle
> feat(shuttle): add options to enable and configure GC

- extensions/warp-ipfs/src/store/mod.rs
- implement a reference of DID for DidExt
> chore: impl didext on did reference

- extensions/warp-ipfs/src/store/conversation.rs
This should fix the issue where authorized group members still can't change the icon/banner.
Issue was brought up here: https://github.com/Satellite-im/UplinkWeb/issues/771
> remove icon/banner from sign/verify
